### ISSUE TITLE
Why exactly one alias?

### ISSUE THREAD

**Issue by otaviomacedo** [ryantenney/passkit4j#21]
Why does the method `PassSigningUtil.firstAlias` require exactly one alias? I am trying to generate p12 files, but they are always generated with two aliases.

**Comment by icova** [comment]
I had the same problem. In my case It worked only specifying as alias the name of the key inside the .p12 certificate.

**Comment by ryantenney** [comment]
There are several options for specifying the alias:
alias(String) - if the p12 file contains more than one alias and the privateKey and signingCertificate aliases are the same
signingCertificateAlias(String) - specify the signing certificate alias
privateKeyAlias(String) - specify the private key alias
