### ISSUE TITLE
Updated API / Values for new iOS passkit ("Wallet") pass types?

### ISSUE THREAD

**Issue by Thomas-Ganter** [ryantenney/passkit4j#26]
Hi, 

with the release (pre-release that is) of the iOS 9 SDK, there is a significant boost to passkit. What are the plans for update / support of these?

-Thomas

**Comment by ryantenney** [comment]
I'm happy to update the library, but unfortunately I no longer have a paid apple developer account. Are you able to send me the updated spec?

**Comment by Alfons109** [comment]
Ryan/Thomas, I have add support for PKBarcodeFormatCode128 which is now natively supported on iOS9.  Please review pull request.

**Comment by ryantenney** [comment]
@Alfons109 Thanks George! Is this the only change to iOS 9 Passkit?

**Comment by Alfons109** [comment]
Thank you for sharing this awesome project.  

Ryan, this was the main passbook feature I needed to integrate for iOS9.  I know that passbook has been re-branded as Wallet to leverage it for mobile payment, but I did not dive into this.  Strictly for passes, I think this is the most relevant change. 

The change added includes:
- new barcode format PKBarcodeFormatCode128
- new barcodes key, that is an array that takes in a dictionary of barcodes, which defines the primary barcode and a fallback.  You can read more about it here.

https://developer.apple.com/library/prerelease/ios/documentation/UserExperience/Reference/PassKit_Bundle/Chapters/TopLevel.html#//apple_ref/doc/uid/TP40012026-CH2-SW1

**Comment by ryantenney** [comment]
Excellent, thanks for the link! I didn't realize that was publicly available.  That definitely clears things up!  I also want to add the NFC support as well, I'll see if I can get to that soon.

**Comment by bimv** [comment]
@ryantenney could you please publish last updates to maven

**Comment by ryantenney** [comment]
Added NFC, published version 2.0.1 to maven central.
