### ISSUE TITLE
Required third party jar files, Please someone mention it

### ISSUE THREAD

**Issue by Kavit900** [ryantenney/passkit4j#28]
Hello Ryan Sir and my other friends, I am new to this field and I want to generate passes using Java, so I want to know what all third party jar files, I will be needing in order to get the project working completely. I have tried running this project but it gives me PKCS12 Mac is invalid error but when run the command to generate passkey it displays Mac verified OK, so I am assuming there is some mistake with the jar files, I have included, Please help me out guys....

**Comment by ryantenney** [comment]
Kavit,

I'm sorry but you're asking the wrong person. I am not an expert at generating PKCS12 files. I have already sent you the resources that I used to learn. 

I wrote this project and am allowing you to use it for free. I cannot be responsible for diagnosing every issue you encounter using it.
