### ISSUE TITLE
 PassSignerImpl 	keystore error in unix deployment

### ISSUE THREAD

**Issue by Abdullah501** [ryantenney/passkit4j#31]
Hello,

i have create console application on windows machine its working fine and able to create pass file from it.
i have done some changes for certificate reading,
	KeyStore ks = KeyStore.getInstance("PKCS12");
		InputStream ksIs = new FileInputStream("certificates/Certificates.p12");
		try {
			ks.load(ksIs, "1234".toCharArray());
		} finally {
			if (ksIs != null) {
				ksIs.close();
			}
		}

		Enumeration aliases = ks.aliases();
		java.security.cert.Certificate cer = null;

		String keyAlias = "";
		while (aliases.hasMoreElements()) {
			keyAlias = (String) aliases.nextElement();
			System.out.print("Key Alias :::\n" + keyAlias + "\n");
			cer = ks.getCertificate(keyAlias);
			System.out.print("getType :::\n" + cer.getType() + "\n");
		}

		PassSigner signer = PassSignerImpl
				.builder()
				.keystore(
						new FileInputStream("certificates\\Certificates.p12"),
						"1234")
				.privateKeyAlias(keyAlias)
				.signingCertificate((X509Certificate) cer)
				.intermediateCertificate(
						new FileInputStream("certificates\\AppleWWDRCA.cer"))
				.build();

		File objFileTemp = new File("testing");

Its working fine , but i deployed this code in unix machine, its giving below error as "com.ryantenney.passkit4j.sign.PassSigningException: Error loading PKCS12 KeyStore
	at com.ryantenney.passkit4j.sign.PassSigningUtil.propagateAsPassSigningException(PassSigningUtil.java:161)" 

is they any compatable issues

thanks
Shaik Abdullah

**Comment by ryantenney** [comment]
You'll want to look at the full stack trace of that exception and find the root cause of this exception and research it. I'm sorry to say that I can't support Java crypto related issues.

**Comment by Abdullah501** [comment]
Hi ryan,
Below is full error
com.ryantenney.passkit4j.sign.PassSigningException: Error loading PKCS12 KeyStore
	at com.ryantenney.passkit4j.sign.PassSigningUtil.propagateAsPassSigningException(PassSigningUtil.java:161)
	at com.ryantenney.passkit4j.sign.PassSigningUtil.loadPKCS12File(PassSigningUtil.java:29)
	at com.ryantenney.passkit4j.sign.PassSignerImpl$Builder.keystore(PassSignerImpl.java:63)
	at com.ryantenney.passkit4j.sign.PassSignerImpl$Builder.keystore(PassSignerImpl.java:50)
Iam using jdk 1.6 version support.
