### ISSUE TITLE
Keystore

### ISSUE THREAD

**Issue by Abdullah501** [ryantenney/passkit4j#32]
KeyStore keystore = KeyStore.getInstance("PKCS12", BouncyCastleProvider.PROVIDER_NAME);
			keystore.load(inputStream, chars(password));			 
			return keystore;

Why we need to specify "BouncyCastleProvider.PROVIDER_NAME" in code?

**Comment by ryantenney** [comment]
Specifying the provider tells java to use Bouncy Castle's KeyStore implementation.  This project uses bouncycastle as the provider for all crypto functions.
