### ISSUE TITLE
Do we have different loading of this jar in unix machine

### ISSUE THREAD

**Issue by Abdullah501** [ryantenney/passkit4j#33]
Hi,
My code working fine in windows machine on java console application. When i integrated this jar files in web and deployed on unix machine iam getting yield errors on mostly certificate.

iam fetching certificate details locally(created virtual folder with certificate p12 and certificate) its working fine. But on unix its througing error.its reading certificate successfully, but 

but in below code its throwing errors,
PassSigner signer = PassSignerImpl.builder().keystore(ks, "1234")
				.privateKeyAlias(keyAlias)
				.signingCertificate((X509Certificate) cer)
				.intermediateCertificate((X509Certificate) cer).build();
		LOG.debug("signer ready1");

Thanks
Shaik Abdullah

**Comment by ryantenney** [comment]
This isn't an issue with this project. Please don't open any additional issues regarding this. The internet is full of resources for you to use.
