### ISSUE TITLE
I'm trying to install the project passkit4j but send me errors PassSerializer class

### ISSUE THREAD

**Issue by angela9mx** [ryantenney/passkit4j#39]
Hello

I am new in your comunity and , could you help me whith this: I am trying install the passkit4j project to create passes from java and sends me errors the PassSerializer class, the version that I have is Java 1.8.0_91, the errors are:

- The method hash () is undefined for the type PassSerializer.OutputStreamHasher
- The method passInformation () is undefined for the type Pass
- The type PassSerializer.OutputStreamHasher must Implement the abstract method inherited OutputStream.write (int)

The pom file does not mark errors, I hope you can help me, thank you
excuse me for my English, I know it is very poor but I hope you understand me, thanks

![image](https://cloud.githubusercontent.com/assets/20995746/17632989/dfffe034-6090-11e6-947a-8a8578a2bad8.png)

Regards

**Comment by ryantenney** [comment]
It sounds like you're opening the project in a Java IDE. The project makes use of [Project Lombok](https://projectlombok.org/) which generates java bytecode. It is already integrated into the Maven build, so you can just run `mvn install`, but if you want to open it in an IDE you'll need to install the Lombok plugin.

**Comment by angela9mx** [comment]
ok, thank you very much, i will install the plugin you mention.
