### ISSUE TITLE
Help while signing 

### ISSUE THREAD

**Issue by josete89** [ryantenney/passkit4j#40]
Hi

I'm getting this error :

passbookscala [ERROR] [08/22/2016 18:43:53.859] Provided KeyStore contains multiple aliases, please specify an alias
passbookscala com.ryantenney.passkit4j.sign.PassSigningException: Provided KeyStore contains multiple aliases, please specify an alias
passbookscala   at com.ryantenney.passkit4j.sign.PassSigningUtil.firstAlias(PassSigningUtil.java:136)
passbookscala   at com.ryantenney.passkit4j.sign.PassSigningUtil.getCertificate(PassSigningUtil.java:100)
passbookscala   at com.ryantenney.passkit4j.sign.PassSignerImpl$Builder.build(PassSignerImpl.java:111)

**Comment by angela9mx** [comment]
Hello josete89
could you tell me how resolve the issue "Provided KeyStore contains multiple aliases, please specify an alias"

Thank you

Regards

**Comment by josete89** [comment]
Hi @angela9mx 

I use this command to see the alias of the certificate:
**openssl pkcs12 -in cert.p12**
the result is-> 
oqszqA==
-----END CERTIFICATE-----
Bag Attributes
    **friendlyName: Alias**

And then I put in the builder chain:
`PassSignerImpl.builder()
      .keystore(new FileInputStream(getResource(config.getString("passbook.certificatePath"))), config.getString("passbook.certKey"))
        .alias("Alias")`

Regards
